# Generated by Django 3.1.1 on 2020-10-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0003_remove_services_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hairCare', models.CharField(max_length=200, null=True)),
                ('makeUpServices', models.CharField(max_length=200, null=True)),
                ('facialMassage', models.CharField(max_length=200, null=True)),
                ('nailArts', models.CharField(max_length=200, null=True)),
                ('hairStyles', models.CharField(max_length=200, null=True)),
                ('pedicure', models.CharField(max_length=200, null=True)),
                ('manicure', models.CharField(max_length=200, null=True)),
                ('hairDye', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
