# Generated by Django 3.1.1 on 2020-10-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0005_auto_20201004_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='hours',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
