# Generated by Django 3.1.1 on 2020-10-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0006_auto_20201004_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
    ]
