# Generated by Django 3.1.1 on 2020-10-09 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0010_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DateTimeField(default=datetime.datetime)),
                ('facialtreatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautyapp.facialtreatment')),
                ('haircare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautyapp.haircare')),
                ('hairstyles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautyapp.hairstyles')),
                ('makeupservices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautyapp.makeupservices')),
                ('manicure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautyapp.manicure')),
                ('nailarts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautyapp.nailarts')),
                ('pedicure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautyapp.pedicure')),
            ],
        ),
    ]
