# Generated by Django 3.1.1 on 2020-10-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0011_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hours',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
